from django.urls import path
from . import views as my_app_view

urlpatterns = [
    path('', my_app_view.home, name = 'homepage'),
    path('login/', my_app_view.loginpage, name='login'),
    path('about-us/', my_app_view.about, name='about'),
    path('ajax/', my_app_view.AjaxHandlerView.as_view(), name='ajax'),
    path('ajax-home/', my_app_view.ajax_home, name='ajax-home'),
    path('signup/', my_app_view.signup, name='signup'),
    path('profile/', my_app_view.profile, name='profile'),
    path('services/', my_app_view.services, name='services'),
    path('techschool/', my_app_view.techschool, name='techschool'),
    path('technews/', my_app_view.technews, name='technews'),
    path('subscribe-js/', my_app_view.subscribe_js, name='subscribe_js'),
    path('subscribe-python/', my_app_view.subscribe_python, name='subscribe_python'),
    path('subscribe-hc/', my_app_view.subscribe_hc, name='subscribe_hc'),
    path('subscribe-fullstack/', my_app_view.subscribe_fullstack, name='subscribe_fullstack'),
    path('subscribe-business/', my_app_view.subscribe_business, name='subscribe_business'),
    path('subscribe-dm/', my_app_view.subscribe_dm, name='subscribe_dm'),
    path('subscribe-blockchain/', my_app_view.subscribe_blockchain, name='subscribe_blockchain'),
    path('learn-html-and-css/', my_app_view.learn_hc , name='learn_hc'),
    path('learn-js/', my_app_view.learn_js , name='learn_js'),
    path('learn-python/', my_app_view.learn_python , name='learn_python'),
    path('learn-blockchain/', my_app_view.learn_blockchain , name='learn_blockchain'),
    path('learn-fullstack/', my_app_view.learn_fullstack , name='learn_fullstack'),
    path('learn-branding/', my_app_view.learn_branding , name='learn_branding'),
    path('learn-js-detail/<int:pk>/', my_app_view.learn_js_detail , name='learn_js_detail'),
    path('learn-python-detail/<int:pk>/', my_app_view.learn_python_detail , name='learn_python_detail'),
    path('test/<slug:course>/<int:pk>', my_app_view.test , name='take_test'),
    path('my-ajax-test/', my_app_view.myajaxtestview, name='ajax-test-view'),
    path('verify/', my_app_view.verify_payments, name = 'verify'),
    path('interests/', my_app_view.interests , name='interests'),
    path('ace/', my_app_view.ace , name='ace'),
    path('logout/', my_app_view.logout_view, name = 'logout'),
    path('post/<int:pk>/', my_app_view.post_detail , name = 'post-detail'),
    path('technews-detail/<int:pk>/', my_app_view.technews_detail , name = 'technews-detail'),
    # path('<slug:filled>/', my_app_view.home, name = 'homepage'),
    ]