# Generated by Django 2.2.2 on 2021-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_js',
            name='description',
            field=models.CharField(blank=True, default='No description stated yet...', max_length=1000, null=True),
        ),
    ]
