# Generated by Django 2.2.2 on 2021-11-09 14:31

from django.db import migrations, models
import my_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics', validators=[my_app.validators.image_validator]),
        ),
    ]
