# Generated by Django 2.2.2 on 2021-12-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20211222_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blockchain_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullstack_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='js_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='python_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_email', models.EmailField(max_length=100)),
                ('customers_phone', models.CharField(max_length=11)),
                ('product_type', models.CharField(choices=[('Learn Js', 'Learn Js'), ('Learn Python', 'Learn Python')], max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('reference', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
