# Generated by Django 2.2.2 on 2022-01-05 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20220105_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn_js',
            name='test_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learn_python',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learn_python',
            name='resources',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learn_python',
            name='task_and_projects',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learn_python',
            name='test_available',
            field=models.BooleanField(default=False),
        ),
    ]
