# Generated by Django 2.2.2 on 2022-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20220105_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn_js',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='json_file'),
        ),
    ]
