# Generated by Django 2.2.2 on 2022-01-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_learn_js_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn_python',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='json_file'),
        ),
    ]
