# Generated by Django 2.2.2 on 2022-01-06 08:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_learn_blockchain_learn_techbusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn_Fullstack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, default='No description stated yet...', max_length=1000, null=True)),
                ('toc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='video_img', validators=[my_app.validators.image_validator])),
                ('video', models.FileField(blank=True, null=True, upload_to='course_video')),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('overview', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('task_and_projects', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resources', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('test_available', models.BooleanField(default=False)),
                ('json_file', models.FileField(blank=True, null=True, upload_to='json_file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
