# Generated by Django 2.2.2 on 2022-01-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20220106_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='html_and_css_paid',
            field=models.BooleanField(default=False),
        ),
    ]
