# Generated by Django 2.2.2 on 2022-01-24 12:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20220118_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='None', max_length=49),
        ),
    ]
