# Generated by Django 2.2.2 on 2022-02-11 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20220125_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('software_type', models.CharField(choices=[('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application'), ('Desktop Application', 'Desktop Application'), ('Chatbot', 'Chatbot'), ('Web Crawler', 'Web Crawler'), ('Others', 'Others')], max_length=30)),
                ('category', models.CharField(choices=[('Personal Project', 'Personal Project'), ('Business Project', 'Business Project'), ('Academic/School Project', 'Academic/School Project'), ('Research Project', 'Research Project'), ('Others', 'Others')], max_length=30)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('date_receieved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
