# Generated by Django 2.2.2 on 2022-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_auto_20220118_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='interests',
            new_name='Interests',
        ),
    ]
